### ISSUE TITLE
Heroku site is broken

### ISSUE THREAD

**Issue by seanohue** [wbruno/dragons-api#2]
I was really excited to learn more about dragons but the Heroku app is experiencing an error.

**Comment by wbruno** [comment]
thank you!
**fixed**: https://github.com/wbruno/dragons-api/commit/ef2c752e2dfeb4d5b44b58d8a1f05e408c00283c


the dragons are alive again!
http://dragons-api.herokuapp.com/api/dragons

**Comment by seanohue** [comment]
Wow, that was fast! Thanks 👍 💯 :1st_place_medal:
